SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE item_cart;
TRUNCATE TABLE item_option;
TRUNCATE TABLE item;
TRUNCATE TABLE cart;
TRUNCATE TABLE member;
TRUNCATE TABLE address;
TRUNCATE TABLE brand;
TRUNCATE TABLE partners;
TRUNCATE TABLE orders;

SET FOREIGN_KEY_CHECKS = 1;
